import json

# Правильные данные с кириллицей
data = {
    "users": [
        {
            "id": "user_1769446825925.whxkh075y",
            "username": "admin@local.dev",
            "name": "admin",
            "email": "admin@local.dev",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "",
            "department": "",
            "telegramId": "",
            "telegramUsername": "",
            "enabledTools": [],
            "createdAt": "2026-01-26T17:00:25.925Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T17:00:25.925Z"
        },
        # Отдел продаж
        {
            "id": "user_001",
            "username": "ivanov@company.com",
            "name": "Иванов Иван",
            "email": "ivanov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Менеджер по продажам",
            "department": "Отдел продаж",
            "telegramId": "ivanov_sales",
            "telegramUsername": "@ivanov_sales",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T19:45:00.000Z"
        },
        {
            "id": "user_002",
            "username": "petrova@company.com",
            "name": "Петрова Анна",
            "email": "petrova@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Старший менеджер",
            "department": "Отдел продаж",
            "telegramId": "petrova_sales",
            "telegramUsername": "@petrova_sales",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T19:30:00.000Z"
        },
        {
            "id": "user_003",
            "username": "sidorov@company.com",
            "name": "Сидоров Петр",
            "email": "sidorov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Менеджер по работе с клиентами",
            "department": "Отдел продаж",
            "telegramId": "sidorov_sales",
            "telegramUsername": "@sidorov_sales",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        {
            "id": "user_004",
            "username": "kuznetsova@company.com",
            "name": "Кузнецова Мария",
            "email": "kuznetsova@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Менеджер по продажам",
            "department": "Отдел продаж",
            "telegramId": "kuznetsova_sales",
            "telegramUsername": "@kuznetsova_sales",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T18:00:00.000Z"
        },
        {
            "id": "user_005",
            "username": "smirnov@company.com",
            "name": "Смирнов Алексей",
            "email": "smirnov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "customer",
            "canSeeAllTasks": True,
            "position": "Руководитель отдела продаж",
            "department": "Отдел продаж",
            "telegramId": "smirnov_head",
            "telegramUsername": "@smirnov_head",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        # Отдел маркетинга
        {
            "id": "user_006",
            "username": "volkov@company.com",
            "name": "Волков Дмитрий",
            "email": "volkov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Маркетолог",
            "department": "Отдел маркетинга",
            "telegramId": "volkov_marketing",
            "telegramUsername": "@volkov_marketing",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        {
            "id": "user_007",
            "username": "sokolova@company.com",
            "name": "Соколова Елена",
            "email": "sokolova@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Контент-менеджер",
            "department": "Отдел маркетинга",
            "telegramId": "sokolova_content",
            "telegramUsername": "@sokolova_content",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T19:00:00.000Z"
        },
        {
            "id": "user_008",
            "username": "morozov@company.com",
            "name": "Морозов Сергей",
            "email": "morozov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "SMM-специалист",
            "department": "Отдел маркетинга",
            "telegramId": "morozov_smm",
            "telegramUsername": "@morozov_smm",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        {
            "id": "user_009",
            "username": "novikova@company.com",
            "name": "Новикова Ольга",
            "email": "novikova@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "SEO-специалист",
            "department": "Отдел маркетинга",
            "telegramId": "novikova_seo",
            "telegramUsername": "@novikova_seo",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T17:30:00.000Z"
        },
        {
            "id": "user_010",
            "username": "fedorov@company.com",
            "name": "Федоров Андрей",
            "email": "fedorov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "customer",
            "canSeeAllTasks": True,
            "position": "Руководитель отдела маркетинга",
            "department": "Отдел маркетинга",
            "telegramId": "fedorov_head",
            "telegramUsername": "@fedorov_head",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        # Отдел разработки
        {
            "id": "user_011",
            "username": "lebedev@company.com",
            "name": "Лебедев Максим",
            "email": "lebedev@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Frontend разработчик",
            "department": "Отдел разработки",
            "telegramId": "lebedev_dev",
            "telegramUsername": "@lebedev_dev",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        {
            "id": "user_012",
            "username": "zaitseva@company.com",
            "name": "Зайцева Виктория",
            "email": "zaitseva@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "Backend разработчик",
            "department": "Отдел разработки",
            "telegramId": "zaitseva_dev",
            "telegramUsername": "@zaitseva_dev",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T19:15:00.000Z"
        },
        {
            "id": "user_013",
            "username": "popov@company.com",
            "name": "Попов Николай",
            "email": "popov@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "QA Engineer",
            "department": "Отдел разработки",
            "telegramId": "popov_qa",
            "telegramUsername": "@popov_qa",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        },
        {
            "id": "user_014",
            "username": "vasiliev@company.com",
            "name": "Васильев Павел",
            "email": "vasiliev@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "executor",
            "canSeeAllTasks": False,
            "position": "DevOps Engineer",
            "department": "Отдел разработки",
            "telegramId": "vasiliev_devops",
            "telegramUsername": "@vasiliev_devops",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": False,
            "lastSeen": "2026-01-26T18:45:00.000Z"
        },
        {
            "id": "user_015",
            "username": "romanova@company.com",
            "name": "Романова Татьяна",
            "email": "romanova@company.com",
            "password": "default123",
            "role": "user",
            "todoRole": "customer",
            "canSeeAllTasks": True,
            "position": "Технический директор",
            "department": "Отдел разработки",
            "telegramId": "romanova_cto",
            "telegramUsername": "@romanova_cto",
            "enabledTools": [],
            "createdAt": "2026-01-26T20:00:00.000Z",
            "isOnline": True,
            "lastSeen": "2026-01-26T20:00:00.000Z"
        }
    ],
    "chats": [],
    "messages": [],
    "todos": [],
    "lists": [],
    "categories": [],
    "settings": {},
    "dataSources": [],
    "feeds": [],
    "products": [],
    "templates": [],
    "collections": [],
    "logs": [],
    "analytics": [],
    "wordstatSearches": [],
    "wordstatCache": []
}

# Сохранение с правильной кодировкой UTF-8
with open('database.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ База данных создана с правильной UTF-8 кодировкой")
print(f"✅ Всего пользователей: {len(data['users'])}")
print(f"✅ Отдел продаж: 5 сотрудников")
print(f"✅ Отдел маркетинга: 5 сотрудников")
print(f"✅ Отдел разработки: 5 сотрудников")
